# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  REPO_NAME_LOWERCASE: mbi-div-b
  IMAGE_NAME_1: mbi-div-b-notebook-base
  IMAGE_NAME_2: mbi-div-b-notebook-cuda
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: cuda-toolkit installation
        uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '11.7.1'
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker 1st image
        id: meta1
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_1 }}

      - name: Build and push 1st Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ env.IMAGE_NAME_1 }}
          file: ${{ env.IMAGE_NAME_1 }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}
      - name: docker-toolkit installation
        run: |
          sudo apt install -y curl
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
          sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
          sudo echo {"runtimes": {"nvidia": {"path": "/usr/bin/nvidia-container-runtime","runtimeArgs": []}},"default-runtime": "nvidia"} >> /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Extract metadata (tags, labels) for Docker 2nd image
        id: meta2
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_2 }}

      - name: Build and push 2nd Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ env.IMAGE_NAME_2 }}
          build-args: |
            BASE_REPO=${{ env.REPO_NAME_LOWERCASE }}
            REGISTRY=${{ env.REGISTRY }}
            }}
          file: ${{ env.IMAGE_NAME_2 }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
